name = "clicky-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ELEVENLABS_VOICE_ID = "kPzsL2i3teMYv0FxEYQ6"
VERTEX_PROJECT_ID = "majestic-fuze-387008"
VERTEX_REGION = "us-east5"
